# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglAR1 <- function(obs, hat, rho) {
    .Call('_FLRebuild_loglAR1', PACKAGE = 'FLRebuild', obs, hat, rho)
}

